#!/bin/bash

sed -i 's/branchType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/inputLSNi2BitThresholdType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/inputLSNi5BitThresholdType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/LEDpresentLSNIType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/LEDpresentType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/lsnSubTypeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/magicSensBaseSetType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/magicSensOTCType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/magicSensOTType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/microSensAirFlowFaultDelayType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/microSensAlarmDelayType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/microSensFanVoltageType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/microSensSensitivityType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/microSensThresholdAirFlowType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/optDisSensType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/optSensType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/simpleSensType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/tempSensType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/radioSensType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/topProAirFlowFaultDelayType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/topProAlarmDelayType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/topProSensitivityType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/topProThresholdAirFlowType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/usTempDisSensType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/usTempSensType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/actionDurationType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/activityTextType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/addrTansmitType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/adminActionType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/operatorActionType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/operatorDirectionType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/avDelayType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/comAddrType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/comparatorEQ_NEQType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/comparatorGT_LT_EQType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/adminStateType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/compoundStateType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/compoundStateWithWildcardType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/countryType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/crcType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/ctieActivationTimeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/ctieActivationTypeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/ctieTypeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/ctieUeeResistanceType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/ctieUeeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/dateTimeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/defaultActionType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/dialerAccountNumberType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/dialerDialingMethodType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/dialerFormatType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/dialerPhoneNumberType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/encodingType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/feedbackDelayType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/feedbackEOLType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/feedBackVariantType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/fullSINumberType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/fullSIQueryType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/hexByte/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/hexLong/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/hexLongPlain/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/holiDayType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/inputSiTypesType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/keydepotActionType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/labelTextType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/languageType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/logActionType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/lsnModeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/lsnTopologyType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/maxPointsType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/modemTypeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/nacElectricEnviroType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/nacFollowupPatternType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/nacPatternType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/nacSyncOptionType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/nacSyncProtocolType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/nacType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/netIDType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/noteType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/offsetEntryType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/onoffType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/onoffBlinkingType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/LEDColorType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/opmActionType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/opmCmdType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/opmTargetType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/panelIDType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/phoneNbrType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/physAddrType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/portType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/portNumberType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/printerTypeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/priorityType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/pwdType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/quietLineType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/relaySiTypesType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/resetModeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/serialNumberType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/siNumberType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/siNumberWithWildcardType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/siSubNumberType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/siSubNumberWithWildcardType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/siTypeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/slotType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/specialDayDateType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/statusActionType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/subjectSITypeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/subTypeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/sumcounterCounterType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/supplyVoltageType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/timePairType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/timeZoneType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/triggerAdminCmdType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/triggerNumberType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/uartFrameType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/uartSpeedType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/usageTypeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/ipAddressType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/usageTypeTypeRestricted/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/usageTypeTypeRestritWithFire/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/usageTypeENOT/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/userIDType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/userIDWithWildcardType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/vasSITypeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/weekDayType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/x400Type/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/flashRateType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/intensityLevelType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/yesnoType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/colorProfileType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/counterIDType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/scopeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/triggerCounterComparatorType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/adiType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/compound_stateType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/functionTypeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/lzType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/mkType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/prioType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/groupType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/ethernetLineType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/flowControlType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/globalCounterIDType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/globalSIIDType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/interfaceNbrType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/localCounterIDType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/localSIIDType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/logicalNodeIDListType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/logicalNodeIDType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/messageFilterType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/netCRCType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/netIdentType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/netLineNumberType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/netLineTypeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/nodeTypeType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
sed -i 's/rsnType/xs:string/g' Main-3-0-0-RedukcjaST.xsd
