<?php

return [
    'countries' => [
        'PL' => 'Polska',
        'US' => 'United States',
        'GB' => 'United Kingdom',
        'DE' => 'Germany',
        'FR' => 'France',
        'IT' => 'Italy',
        'ES' => 'Spain',
        'CA' => 'Canada',
        'AU' => 'Australia',
        'JP' => 'Japan',
        'CN' => 'China',
        'IN' => 'India',
        'BR' => 'Brazil',
        'MX' => 'Mexico',
        'RU' => 'Russia',
        'ZA' => 'South Africa',
        'KR' => 'South Korea',
        'AR' => 'Argentina',
        'NL' => 'Netherlands',
        'SE' => 'Sweden',
    ],

    'timezones' => [
        'Pacific/Midway'       => '(UTC-11:00) Midway Island',
        'Pacific/Samoa'        => '(UTC-11:00) Samoa',
        'Pacific/Honolulu'     => '(UTC-10:00) Hawaii',
        'America/Anchorage'    => '(UTC-09:00) Alaska',
        'America/Los_Angeles'  => '(UTC-08:00) Pacific Time (US & Canada)',
        'America/Denver'       => '(UTC-07:00) Mountain Time (US & Canada)',
        'America/Chicago'      => '(UTC-06:00) Central Time (US & Canada)',
        'America/New_York'     => '(UTC-05:00) Eastern Time (US & Canada)',
        'America/Caracas'      => '(UTC-04:30) Caracas',
        'America/Sao_Paulo'    => '(UTC-03:00) Brasilia',
        'Atlantic/Azores'      => '(UTC-01:00) Azores',
        'Europe/London'        => '(UTC+00:00) London',
        'Europe/Berlin'        => '(UTC+01:00) Berlin, Paris, Rome',
        'Europe/Warsaw'        => '(UTC+01:00) Warsaw',
        'Europe/Kiev'          => '(UTC+02:00) Kyiv',
        'Europe/Moscow'        => '(UTC+03:00) Moscow',
        'Asia/Dubai'           => '(UTC+04:00) Dubai',
        'Asia/Karachi'         => '(UTC+05:00) Islamabad, Karachi',
        'Asia/Dhaka'           => '(UTC+06:00) Dhaka',
        'Asia/Bangkok'         => '(UTC+07:00) Bangkok',
        'Asia/Hong_Kong'       => '(UTC+08:00) Hong Kong, Beijing',
        'Asia/Tokyo'           => '(UTC+09:00) Tokyo',
        'Australia/Sydney'     => '(UTC+10:00) Sydney',
        'Pacific/Auckland'     => '(UTC+12:00) Auckland',
    ],

    'languages' => [
        'PL' => 'Polski',
        'EN' => 'English',
        'DE' => 'Deutsch',
        'FR' => 'Français',
    ],
];
